'use strict';
// Opt-in mode. Free play keeps its existing notes, clips, sounds and timing.
const gameToggle=document.createElement('button');gameToggle.id='gameToggle';gameToggle.textContent='Game Mode';gameToggle.setAttribute('aria-pressed','false');$('gazeArtToggle').after(gameToggle);
const gamePanel=document.createElement('section');gamePanel.id='gamePanel';gamePanel.hidden=true;gamePanel.innerHTML=`<div class="game-controls"><select id="gameSong" aria-label="Game melody"></select><label>BPM <input id="gameBpm" type="number" min="20" max="140" value="72"></label><button id="gameStart">Start / restart</button><button id="gamePause" disabled>Pause</button><button id="gameExit">Return to free play</button></div><div class="game-controls"><label class="game-upload">Upload MIDI / score <input id="gameUpload" type="file" accept=".mid,.midi,.txt,.json"></label><select id="gameTrack" aria-label="MIDI melody track" hidden></select><button id="gameTemplate">Download score template</button><label><input id="gameBacking" type="checkbox" checked>Beat accompaniment</label></div><p id="gameStatus" role="status">Choose a melody. Look at the lit donut for 120 ms. A new note allows a new hit, even on the same donut.</p><div id="gamePhrase"></div><small id="gameImportInfo">Upload stays on this computer. MIDI: one melody track, up to eight pitches, constant tempo. Numbered TXT: 1–8 = C4–C5, 0 = rest; 5:2 = two beats. MP3/WAV transcription is not included.</small>`;
dash.querySelector('.score-heading').after(gamePanel);
const gameCanvas=document.createElement('canvas');gameCanvas.id='gameCanvas';gameCanvas.setAttribute('aria-label','Game melody targets and remaining note time');gameCanvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:1';gameCanvas.hidden=true;fit.append(gameCanvas);
const gameStyle=document.createElement('style');gameStyle.textContent='#gameToggle{display:none;width:100%;font-size:11px;margin-top:5px;padding:6px}.controller-mode #gameToggle{display:block}.game-mode .score-card{grid-template-rows:auto auto minmax(0,1fr) 24px}.game-mode #gamePanel{display:block}#gamePanel{padding:8px 10px;background:#f1f6f1;border:1px solid #c5d9cc;border-radius:10px}#gamePanel[hidden]{display:none!important}.game-controls{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-bottom:5px}.game-controls button,.game-controls select,.game-controls label{font-size:11px;padding:4px}.game-controls select{width:auto;max-width:260px}.game-controls input[type=number]{width:58px;padding:3px}.game-upload input{max-width:180px;font-size:10px}#gameStatus{font-size:12px;margin:5px 0}#gamePhrase{display:flex;gap:5px;overflow:hidden;height:24px;align-items:center}#gamePhrase span{padding:2px 6px;border-radius:5px;background:#fff;font-size:11px;white-space:nowrap}#gamePhrase span.current{background:#397f6c;color:#fff}#gameImportInfo{font-size:10px;display:block;line-height:1.3}.game-mode #startDuet{display:none}@media(max-height:700px){#gameImportInfo{display:none}#gamePanel{padding:5px}.game-controls{margin-bottom:2px}}';document.head.append(gameStyle);
const gameSongs=[DonutGame.textScore('1 1 5 5 6 6 5:2 | 4 4 3 3 2 2 1:2 | 5 5 4 4 3 3 2:2 | 5 5 4 4 3 3 2:2 | 1 1 5 5 6 6 5:2 | 4 4 3 3 2 2 1:2','Twinkle, Twinkle, Little Star'),DonutGame.textScore('3 2 1 2 3 3 3:2 | 2 2 2:2 3 5 5:2 | 3 2 1 2 3 3 3 3 | 2 2 3 2 1:4','Mary Had a Little Lamb'),DonutGame.textScore('1 2 3 1 | 1 2 3 1 | 3 4 5:2 | 3 4 5:2 | 5:0.5 6:0.5 5:0.5 4:0.5 3 1 | 5:0.5 6:0.5 5:0.5 4:0.5 3 1 | 1 5 1:2 | 1 5 1:2','Frère Jacques')];
let gameEnabled=false,gameSession=null,gamePausedAt=null,gameSaved=null,gameImported=[],gameLastPaint=0,gameLastBeat=-99,gameVoiceSet=new Set(),gameOutcome=null;
function gameModeActive(){return gameEnabled;}
for(const s of gameSongs)$('gameSong').add(new Option(s.title,String($('gameSong').options.length)));
function gameSelected(){return gameSongs[Number($('gameSong').value)];}
function gameSilence(){for(const v of gameVoiceSet)instrument.release(v);gameVoiceSet.clear();midiOut.panic();}
function gameExit(){gameSilence();gameEnabled=false;gameSession=null;gameOutcome=null;gamePausedAt=null;gameCanvas.hidden=true;gamePanel.hidden=true;document.body.classList.remove('game-mode');gameToggle.setAttribute('aria-pressed','false');gameToggle.textContent='Game Mode';dwell.reset();if(gameSaved){$('lastNote').textContent=gameSaved.lastNote;audioEnabled=gameSaved.audio;setPhase(gameSaved.phase);$('audioButton').textContent=audioEnabled?'Ⅱ Pause sound':'▶ Resume playing';$('audioState').textContent=audioEnabled?'Sound on · Space to pause':'Sound paused';gameSaved=null;}}
function enterGame(){if(researchRunning()||calibrating||cognitiveEvidence.capture||recording){toast('Finish recording, research or reference capture before entering Game Mode.');return;}gameSaved={audio:audioEnabled,phase,lastNote:$('lastNote').textContent};gameEnabled=true;stopBacking();stateSoundscapes.stop(true);stopStateSound();instrument.stop();dwell.reset();gamePanel.hidden=false;document.body.classList.add('game-mode');gameToggle.setAttribute('aria-pressed','true');gameToggle.textContent='Game Mode · on';cognitiveEvidence.invalidate('Game visuals and task changed; capture a new reference after free play resumes');gameStatus('Choose a song and press Start. Four count-in beats, then look at each lit donut for 120 ms.');}
gameToggle.onclick=()=>gameEnabled?gameExit():enterGame();$('gameExit').onclick=gameExit;
function gameStatus(text){$('gameStatus').textContent=text;}
function stopGameForEdit(){gameSilence();gameSession=null;gameOutcome=null;gamePausedAt=null;$('gamePause').disabled=true;$('lastNote').textContent='Game ready · follow the lit donut';gameStatus('Score ready. Press Start for a four-beat count-in.');}
$('gameSong').onchange=()=>{stopGameForEdit();$('gameBpm').value=Math.min(100,Math.round(gameSelected().bpm));};
$('gameBpm').onchange=stopGameForEdit;
$('gameStart').onclick=async()=>{
 if(!gameEnabled)return;if(source==='replay'){gameStatus('Use live Neon or Mouse simulation for the game.');return;}
 if(source==='live'&&(!sample||!sample.worn||!sample.surfaceValid||performance.now()-sampleReceived>=500)){gameStatus('Pair Neon, wear the glasses and show all four markers before starting.');return;}
 const s=gameSelected(),bpm=Number($('gameBpm').value);if(!Number.isFinite(bpm)||bpm<20||bpm>140){gameStatus('Choose 20–140 BPM.');return;}
 const shortest=Math.min(...s.events.map(e=>e.end-e.start));if(shortest*60000/bpm<300){gameStatus('These notes are too short for gaze. Lower BPM to '+Math.floor(shortest*60000/300)+' or simplify the score.');return;}
 if(!document.body.classList.contains('controller-mode'))await toggleController(true);
 try{await instrument.start();}catch(e){gameStatus('Audio could not start: '+e.message);return;}if(!gameEnabled)return;
 audioEnabled=true;$('audioButton').textContent='Ⅱ Pause sound';$('audioState').textContent='Sound on · Game Mode';setPhase('look');gameSilence();gameSession=new DonutGame.RhythmGame();gameSession.start(s,bpm,performance.now());gameSession.source=source;$('lastNote').textContent='Game ready · follow the lit donut';gamePausedAt=null;gameLastBeat=-99;gameOutcome=null;$('gamePause').disabled=false;$('gamePause').textContent='Pause';
};
function pauseGame(reason){if(!gameSession||gameSession.done||gamePausedAt!==null)return;gamePausedAt=performance.now();gameSession.since=null;gameSilence();$('gamePause').textContent='Resume';gameStatus('Paused · '+reason);}
$('gamePause').onclick=async()=>{if(gamePausedAt===null){pauseGame('press Resume when ready');return;}if(!gameSession)return;const resumedSession=gameSession;if(source!==gameSession.source){gameStatus('Input source changed. Restart the song.');return;}if(source==='live'&&(!sample||!sample.worn||!sample.surfaceValid||performance.now()-sampleReceived>=500)){gameStatus('Waiting for worn, located live gaze before resuming.');return;}try{await instrument.start();}catch(e){gameStatus(e.message);return;}if(!gameEnabled||gameSession!==resumedSession||gamePausedAt===null)return;audioEnabled=true;gameSession.startTime+=performance.now()-gamePausedAt;gameSession.last=null;gamePausedAt=null;$('gamePause').textContent='Pause';$('audioButton').textContent='Ⅱ Pause sound';$('audioState').textContent='Sound on · Game Mode';};
function gameVoice(midi,at,duration,level,tone='piano'){if(!localSoundEnabled())return;const v=instrument.voice(midi,false,tone,at,level);if(!v)return;gameVoiceSet.add(v);if(v.gain){v.gain.gain.cancelScheduledValues(at+.1);v.gain.gain.setValueAtTime(.35*level,at+.1);v.gain.gain.exponentialRampToValueAtTime(.001,at+Math.max(.15,duration));}try{v.osc.stop(at+Math.max(.15,duration)+.05);v.lfo?.stop(at+Math.max(.15,duration)+.05);}catch{}}
function gameSoundHit(e,beat){const seconds=60/gameSession.bpm;const delay=Math.max(0,Math.min(Math.ceil(beat*4)/4-beat,e.end-beat-.04)*seconds),at=instrument.ctx.currentTime+delay;gameVoice(e.midi,at,Math.max(.18,(e.end-beat)*seconds-delay),.85);midiOut.note(e.midi,0,Math.max(100,((e.end-beat)*seconds-delay)*1000),delay*1000);$('lastNote').textContent=`Game · ${noteLabel(e.midi)} · ${gameSession.hits} hits`;onGazeArtNote(e.zone);onCognitiveNote();log('game_note',{midi:e.midi,zone:e.zone,index:gameSession.index,source});}
function addGameScore(s){stopGameForEdit();if(gameSongs.length>12){gameSongs.pop();$('gameSong').remove($('gameSong').options.length-1);}gameSongs.push(s);$('gameSong').add(new Option(s.title,String(gameSongs.length-1)));$('gameSong').value=String(gameSongs.length-1);$('gameBpm').value=Math.min(100,Math.round(s.bpm));gameStatus(`Loaded ${s.events.length} notes. Pitch labels on the mat show the game mapping. Press Start.`);}
$('gameUpload').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024){gameStatus('Maximum upload size: 2 MB.');return;}try{if(/\.midi?$/i.test(f.name)){gameImported=DonutGame.midiScores(await f.arrayBuffer());$('gameTrack').replaceChildren(new Option('Choose a MIDI melody track',''));gameImported.forEach((t,i)=>{const o=new Option(t.title+(t.error?' · unavailable':` · ${t.score.events.length} notes`),String(i));$('gameTrack').add(o);});$('gameTrack').hidden=false;gameStatus('MIDI read locally. Select the melody track; chord tracks are not playable.');}else if(/\.(txt|json)$/i.test(f.name)){const s=DonutGame.textScore(await f.text(),f.name);addGameScore(s);$('gameTrack').hidden=true;}else throw Error('Upload .mid, .midi, .txt or .json. Audio transcription is not included.');}catch(error){gameStatus('Upload not loaded: '+error.message);}};
$('gameTrack').onchange=()=>{if($('gameTrack').value==='')return;const t=gameImported[Number($('gameTrack').value)];if(t.error){gameStatus(t.error);return;}addGameScore(t.score);};
$('gameTemplate').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({title:'My melody',bpm:72,notes:[{note:60,beats:1},{note:60,beats:1},{note:67,beats:2},{note:null,beats:1}]},null,2)],{type:'application/json'}));a.download='donut-game-score.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
function paintGame(now,out){const w=fit.clientWidth,h=fit.clientHeight,dpr=Math.min(devicePixelRatio||1,2);gameCanvas.hidden=!gameEnabled;if(!gameEnabled||!w||!h)return;if(gameCanvas.width!==Math.round(w*dpr)||gameCanvas.height!==Math.round(h*dpr)){gameCanvas.width=Math.round(w*dpr);gameCanvas.height=Math.round(h*dpr);}const c=gameCanvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);const s=gameSession?.score||gameSelected();
 c.save();c.beginPath();c.rect(0,0,w,h);for(const x of [0,.85*w])for(const y of [0,.78*h])c.rect(x,y,.15*w,.22*h);c.clip('evenodd');
 for(let i=0;i<8;i++){const z=ZONES[i],x=z.x*w,y=z.y*h,r=z.r*w*.86;const target=out&&!out.done&&out.event.zone===i;const next=out?.next?.zone===i&&!target;
  if(target){const g=c.createRadialGradient(x,y,r*.3,x,y,r*1.25);g.addColorStop(0,out.fired?'rgba(62,172,128,.3)':'rgba(255,202,82,.22)');g.addColorStop(1,'rgba(255,202,82,0)');c.fillStyle=g;c.beginPath();c.arc(x,y,r*1.25,0,Math.PI*2);c.fill();c.strokeStyle=out.fired?'#3b9d7e':'#dfa32b';c.lineWidth=5;c.beginPath();c.arc(x,y,r,-Math.PI/2,-Math.PI/2+2*Math.PI*(out.active?out.remaining:1));c.stroke();}
  else if(next){c.strokeStyle='#85b9a7';c.lineWidth=2;c.setLineDash([4,4]);c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.stroke();c.setLineDash([]);}
  const label=s.pitches[i]===undefined?'—':noteLabel(s.pitches[i]);c.font=`600 ${Math.max(10,w*.014)}px system-ui`;c.textAlign='center';c.fillStyle='#fffaf0';c.fillRect(x-25,y-r-22,50,19);c.fillStyle='#355b50';c.fillText(label,x,y-r-8);
 }c.restore();
}
function tickGame(now){requestAnimationFrame(tickGame);if(!gameEnabled)return;if(now-gameLastPaint<30)return;gameLastPaint=now;
 const inConsole=document.body.classList.contains('controller-mode');if(gameSession&&!gameSession.done&&gamePausedAt===null){const fresh=sample&&now-sampleReceived<500,worn=fresh&&sample.worn,located=worn&&sample.surfaceValid;
  if(!inConsole||document.hidden||!audioEnabled||instrument.ctx?.state!=='running'||source!==gameSession.source||(source==='live'&&!located)){pauseGame('restore the console, audio and gaze connection, then press Resume');}
  else {const zone=located?zoneAt(sample.x,sample.y):-1;gameOutcome=gameSession.update(now,zone,!!located);const o=gameOutcome;
   if(o.done){gameSilence();$('gamePause').disabled=true;gameStatus(`Finished · ${gameSession.hits}/${gameSession.score.events.length} notes hit · ${gameSession.misses} missed. Restart or return to free play.`);}
   else {if(o.hit)gameSoundHit(o.hit,o.beat);const beat=Math.floor(o.beat);if(beat!==gameLastBeat){gameLastBeat=beat;if($('gameBacking').checked){const c=instrument.ctx;if(beat<0)gameVoice(84,c.currentTime,.16,.13);else if(beat%4===0){const root=gameSession.score.pitches[0];gameVoice(Math.max(0,root-12),c.currentTime,60/gameSession.bpm*2,.18);gameVoice(Math.max(0,root-5),c.currentTime,60/gameSession.bpm*2,.08);}else gameVoice(84,c.currentTime,.1,.035);}}
    gameStatus(o.beat<0?`Count in · ${Math.ceil(-o.beat)} · prepare ${noteLabel(o.event.midi)}`:`${o.active?(o.fired?'Hit ✓':'Look at '+noteLabel(o.event.midi)):'Rest · next '+noteLabel(o.event.midi)} · ${gameSession.hits} hits · ${gameSession.misses} missed · ${gameSession.index+1}/${gameSession.score.events.length}`);
   }
  }
 }
 for(const v of gameVoiceSet)if(v.ended||v.released)gameVoiceSet.delete(v);
 const s=gameSession?.score||gameSelected(),index=gameSession?.index||0;const phrase=s.events.slice(index,index+8).map((e,i)=>{const el=document.createElement('span');el.textContent=noteLabel(e.midi);el.className=i===0?'current':'';return el;});$('gamePhrase').replaceChildren(...phrase);paintGame(now,gameOutcome);
}
requestAnimationFrame(tickGame);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseGame('tab hidden');});window.addEventListener('pagehide',()=>{if(gameEnabled)gameSilence();});
