'use strict';
let researchLocked=[];
function lockResearchControls(lock){if(lock){researchLocked=[...document.querySelectorAll('#noteControls select, #source, #dwell, #bodyEnabled, #preset, #mapping, #strength, .sample-row input, .sample-row button, #startDuet, #studioDemo, #connectEyes')].map(el=>[el,el.disabled]);for(const [el] of researchLocked)el.disabled=true;}else{for(const [el,disabled] of researchLocked)el.disabled=disabled;researchLocked=[];}}
let researchSession=null,researchBlock=null,researchIndex=0,researchLastSample=null;
// Each visible/memory pair uses identical notes; shuffle pair and within-pair order per session.
const researchPairs=[[0,2,4,7],[7,4,2,0],[0,3,5,7]];
let researchTasks=[];
function makeResearchTasks(){
 const pairs=researchPairs.map((notes,pair)=>({notes,pair}));
 for(let i=pairs.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pairs[i],pairs[j]]=[pairs[j],pairs[i]];}
 return pairs.flatMap(({notes,pair})=>(Math.random()<.5?['visible','memory']:['memory','visible']).map(kind=>({kind,pair,notes:[...notes]})));
}
const researchPanel=document.createElement('section');researchPanel.className='panel';
researchPanel.innerHTML=`<h3>Research · guided melody → free play</h3><p>Model: untrained. Collect baselines and labels first; a difficult task is not automatically confusion. Uses scene-matched mat data at about 30 Hz, without validated fixation or blink events.</p><label><input id="researchConsent" type="checkbox">I consent to local session storage of gaze, playing and self-reports; no video</label><div><button id="researchStart">Start ~6-minute session</button><button id="researchCancel">End & return to free play</button><button id="researchExport" disabled>Export research data</button></div><p id="researchStatus">45 s baseline + three matched visible / memory melody pairs (six 30 s blocks), each followed by self-report. A short session does not validate a classifier.</p><div id="researchRatings" hidden><p>Reflect on the whole block just completed. If your state varied substantially, choose Mixed / unsure.</p><label>Attention <select id="researchAttention"><option value="">Select</option><option value="on_task">Mostly on task</option><option value="off_task">Mostly other thoughts</option><option value="mixed">Mixed / unsure</option></select></label><div id="ratingFields"></div><button id="researchNext">Save report & start next block</button></div><p>Your clips are retained. During collection, a standard synth piano replaces them and accompaniment, body modulation and region tones are off. End at any time; restart accompaniment manually afterward.</p>`;
musicPanel.after(researchPanel);
for(const [id,label] of [['confusion','Confused'],['stuck','Stuck'],['effort','Effort']]){const l=document.createElement('label');l.textContent=label;const sel=document.createElement('select');sel.id='rating-'+id;sel.add(new Option('Select',''));for(let i=0;i<=4;i++)sel.add(new Option(`${i} ${i===0?'None':i===4?'Very strong':''}`,String(i)));sel.add(new Option('Mixed / unsure','mixed'));l.append(sel);$('ratingFields').append(l);}
const researchBanner=document.createElement('div');researchBanner.hidden=true;researchBanner.style.cssText='position:fixed;top:34px;left:50%;transform:translateX(-50%);z-index:310;background:#fff9df;color:#302b24;padding:8px;border:1px solid #ccae65;border-radius:8px;max-width:55vw;text-align:center;pointer-events:none';document.body.append(researchBanner);
function researchRunning(){return !!researchSession?.active;}
function researchToneOverride(){return researchRunning();}
function captureResearchSample(s,now){if(!researchRunning()||!researchBlock||researchBlock.finished)return;if(source==='live'&&s.deviceTimestamp===researchLastSample)return;researchLastSample=s.deviceTimestamp;researchBlock.samples.push({t:now-researchBlock.start,deviceTimestamp:s.deviceTimestamp??null,x:s.x,y:s.y,worn:s.worn,surfaceValid:s.surfaceValid,pupilLeft:s.pupilLeft,pupilRight:s.pupilRight});}
function onResearchNote(zone){if(!researchRunning()||!researchBlock||researchBlock.finished||researchBlock.kind==='baseline')return;const expected=researchBlock.notes[researchBlock.progress%researchBlock.notes.length],correct=zone===expected;researchBlock.events.push({t:performance.now()-researchBlock.start,zone,expected,correct});if(correct)researchBlock.progress++;}
function beginResearchBlock(){const task=researchIndex<0?{kind:'baseline',notes:[]}:researchTasks[researchIndex];researchBlock={...task,start:performance.now(),duration:researchIndex<0?45000:30000,progress:0,samples:[],events:[],finished:false};researchSession.blocks.push(researchBlock);researchLastSample=null;$('researchRatings').hidden=true;for(const id of ['researchAttention','rating-confusion','rating-stuck','rating-effort'])$(id).value='';setPhase(researchIndex<0?'prepare':'look');}
$('researchStart').onclick=async()=>{
 if(typeof gameModeActive==='function'&&gameModeActive()){toast('Return to free play before starting a research session or reference capture.');return;}
 if(!$('researchConsent').checked){toast('Confirm consent to local collection first.');return;}
 if(recording||calibrating||source==='replay'||studioDemo){toast('Stop regular recording / calibration and the eye demo. Select live or mouse mode.');return;}
 if(researchRunning())return;
 if(typeof cognitiveEvidence!=='undefined'&&cognitiveEvidence.capture){toast('Finish the eye reference capture first.');return;}
 if(researchSession&&!researchSession.exported){toast('Export the previous research session before starting another.');return;}
 if(source==='live'&&(!sample||!sample.worn||!sample.surfaceValid||performance.now()-sampleReceived>500)){toast('Connect the glasses and locate the mat first.');return;}
 if(!audioEnabled)await toggleAudio();if(!audioEnabled)return;
 researchSession={schema:'donut-midi-research/2',createdAt:new Date().toISOString(),id:crypto.randomUUID(),source,synthetic:source!=='live',sampling:'scene-matched ~30Hz; not fixation events',active:true,modelStatus:'untrained',blocks:[],mapping:structuredClone(config),savedBody:$('bodyEnabled').checked};researchIndex=-1;researchTasks=makeResearchTasks();researchSession.taskOrder=structuredClone(researchTasks);researchSession.protocol='matched-melody-2; randomized pair and within-pair order; self-paced';
 $('backingMode').value='off';stopBacking();stopStateSound();$('curveSound').checked=false;$('bodyEnabled').checked=false;settingsChanged();lockResearchControls(true);researchBanner.hidden=false;$('researchStart').disabled=true;$('researchExport').disabled=true;beginResearchBlock();
};
function finishResearch(reason){if(!researchSession)return;if(researchBlock&&!researchBlock.finished){researchBlock.aborted=true;researchBlock.finished=true;}researchSession.active=false;lockResearchControls(false);researchSession.endReason=reason;researchSession.exported=false;researchBanner.hidden=true;$('researchRatings').hidden=true;$('researchExport').disabled=false;$('researchStart').disabled=false;$('bodyEnabled').checked=researchSession.savedBody;settingsChanged();setPhase('look');$('researchStatus').textContent='Session ended. Export and return to free play. The model remains untrained; restart accompaniment manually.';}
$('researchCancel').onclick=()=>finishResearch('participant-ended');
$('researchConsent').onchange=()=>{if(!$('researchConsent').checked&&researchRunning())finishResearch('consent-stopped');};
$('researchNext').onclick=()=>{if(!researchRunning()||!researchBlock.finished)return;const attention=$('researchAttention').value,ratings=Object.fromEntries(['confusion','stuck','effort'].map(k=>[k,$('rating-'+k).value]));if(!attention||Object.values(ratings).some(x=>x==='')){toast('Complete all fields; Mixed / unsure is valid.');return;}researchBlock.report={attention,...ratings,scope:'whole completed block; retrospective'};researchIndex++;if(researchIndex>=researchTasks.length)finishResearch('completed');else beginResearchBlock();};
setInterval(()=>{if(!researchRunning()||!researchBlock||researchBlock.finished)return;if(document.hidden||source!==researchSession.source){finishResearch('interrupted');return;}const elapsed=performance.now()-researchBlock.start,left=Math.max(0,Math.ceil((researchBlock.duration-elapsed)/1000));let cue=researchBlock.kind==='baseline'?'Look naturally at the mat; keep lighting and position stable':researchBlock.kind==='memory'&&elapsed>6000?'Repeat the melody from memory; forgetting is okay':researchBlock.notes.map(n=>n+1).join(' → ');const msg=`${researchIndex<0?'Baseline capture':`Melody ${researchIndex+1}/6 · ${researchBlock.kind==='memory'?'Memory':'Visible'} melody`} · ${left} s · ${cue}`;researchBanner.textContent=msg;$('researchStatus').textContent=msg;if(left===0){researchBlock.finished=true;researchBlock.summary={samples:researchBlock.samples.length,validFraction:researchBlock.samples.length?researchBlock.samples.filter(s=>s.worn&&s.surfaceValid).length/researchBlock.samples.length:0};setPhase('prepare');instrument.stop();if(researchIndex<0){const values=researchBlock.samples.map(s=>pupil(s)).filter(v=>v!==null).sort((a,b)=>a-b);if(values.length>=150){baseline=values[Math.floor(values.length/2)];baselineReady=true;smoothed=baseline;researchBlock.pupilReference=baseline;}researchIndex=0;beginResearchBlock();}else{$('researchRatings').hidden=false;researchBanner.textContent='Block complete. Report your feelings in the research panel.';}}},150);
$('researchExport').onclick=()=>{if(!researchSession||researchRunning())return;const blob=new Blob([JSON.stringify(researchSession)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='donut-midi-research-'+researchSession.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);researchSession.exported=true;};
window.addEventListener('beforeunload',e=>{if(researchSession&&!researchSession.exported){e.preventDefault();e.returnValue='';}});
