'use strict';
let researchLocked=[];
function lockResearchControls(lock){if(lock){researchLocked=[...document.querySelectorAll('#noteControls select, #source, #dwell, #bodyEnabled, #preset, #mapping, #strength, .sample-row input, .sample-row button, #startDuet, #studioDemo, #connectEyes')].map(el=>[el,el.disabled]);for(const [el] of researchLocked)el.disabled=true;}else{for(const [el,disabled] of researchLocked)el.disabled=disabled;researchLocked=[];}}
let researchSession=null,researchBlock=null,researchIndex=0,researchLastSample=null;
const researchTasks=[{kind:'visible',notes:[0,2,4,7]},{kind:'memory',notes:[0,4,1,5,2,6,7]},{kind:'visible',notes:[7,4,2,0]},{kind:'memory',notes:[2,5,1,6,3,7,0]},{kind:'visible',notes:[0,3,5,7]},{kind:'memory',notes:[7,3,6,2,5,1,0]}];
const researchPanel=document.createElement('section');researchPanel.className='panel';
researchPanel.innerHTML=`<h3>研究模式 · 跟奏采集 → 自由演奏</h3><p>模型状态：未训练。先采集个人参考与标签，不把困难任务自动当作困惑。本轮使用现有约 30 Hz 桌垫数据，不包含经过验证的 fixation / blink 事件。</p><label><input id="researchConsent" type="checkbox">同意在本机暂存本轮眼动、演奏与自述；不保存视频</label><div><button id="researchStart">开始约 6 分钟采集</button><button id="researchCancel">结束并回到自由演奏</button><button id="researchExport" disabled>导出研究数据</button></div><p id="researchStatus">45 秒参考观看 + 六段跟奏。每段 30 秒，随后标记感受。短时采集不等于已验证分类器。</p><div id="researchRatings" hidden><p>请回顾刚结束的整段任务。若期间状态变化很大，选择混合／不确定。</p><label>注意 <select id="researchAttention"><option value="">请选择</option><option value="on_task">主要在任务上</option><option value="off_task">主要在其他想法上</option><option value="mixed">混合／不确定</option></select></label><div id="ratingFields"></div><button id="researchNext">保存自述，开始下一段</button></div><p>音频上传仍保留；采集时暂用统一合成钢琴，关闭伴奏、身体调制与创作状态音。可随时结束；完成后自行重新开启伴奏。</p>`;
musicPanel.after(researchPanel);
for(const [id,label] of [['confusion','困惑'],['stuck','卡住'],['effort','费力']]){const l=document.createElement('label');l.textContent=label;const sel=document.createElement('select');sel.id='rating-'+id;sel.add(new Option('请选择',''));for(let i=0;i<=4;i++)sel.add(new Option(`${i} ${i===0?'无':i===4?'很强':''}`,String(i)));sel.add(new Option('混合／不确定','mixed'));l.append(sel);$('ratingFields').append(l);}
const researchBanner=document.createElement('div');researchBanner.hidden=true;researchBanner.style.cssText='position:fixed;top:34px;left:50%;transform:translateX(-50%);z-index:310;background:#fff9df;color:#302b24;padding:8px;border:1px solid #ccae65;border-radius:8px;max-width:55vw;text-align:center;pointer-events:none';document.body.append(researchBanner);
function researchRunning(){return !!researchSession?.active;}
function researchToneOverride(){return researchRunning();}
function captureResearchSample(s,now){if(!researchRunning()||!researchBlock||researchBlock.finished)return;if(source==='live'&&s.deviceTimestamp===researchLastSample)return;researchLastSample=s.deviceTimestamp;researchBlock.samples.push({t:now-researchBlock.start,deviceTimestamp:s.deviceTimestamp??null,x:s.x,y:s.y,worn:s.worn,surfaceValid:s.surfaceValid,pupilLeft:s.pupilLeft,pupilRight:s.pupilRight});}
function onResearchNote(zone){if(!researchRunning()||!researchBlock||researchBlock.finished||researchBlock.kind==='baseline')return;const expected=researchBlock.notes[researchBlock.progress%researchBlock.notes.length],correct=zone===expected;researchBlock.events.push({t:performance.now()-researchBlock.start,zone,expected,correct});if(correct)researchBlock.progress++;}
function beginResearchBlock(){const task=researchIndex<0?{kind:'baseline',notes:[]}:researchTasks[researchIndex];researchBlock={...task,start:performance.now(),duration:researchIndex<0?45000:30000,progress:0,samples:[],events:[],finished:false};researchSession.blocks.push(researchBlock);researchLastSample=null;$('researchRatings').hidden=true;for(const id of ['researchAttention','rating-confusion','rating-stuck','rating-effort'])$(id).value='';setPhase(researchIndex<0?'prepare':'look');}
$('researchStart').onclick=async()=>{
 if(!$('researchConsent').checked){toast('请先同意本轮本机采集。');return;}
 if(recording||calibrating||source==='replay'||studioDemo){toast('请先结束普通记录／瞳孔采集，关闭演示，使用实时或鼠标模拟。');return;}
 if(researchRunning())return;
 if(researchSession&&!researchSession.exported){toast('请先导出上一轮研究数据，再开始新一轮。');return;}
 if(source==='live'&&(!sample||!sample.worn||!sample.surfaceValid||performance.now()-sampleReceived>500)){toast('先连接眼镜并定位桌垫。');return;}
 if(!audioEnabled)await toggleAudio();if(!audioEnabled)return;
 researchSession={schema:'donut-midi-research/1',createdAt:new Date().toISOString(),id:crypto.randomUUID(),source,synthetic:source!=='live',sampling:'scene-matched ~30Hz; not fixation events',active:true,modelStatus:'untrained',blocks:[],mapping:structuredClone(config),savedBody:$('bodyEnabled').checked};researchIndex=-1;
 $('backingMode').value='off';stopBacking();stopStateSound();$('curveSound').checked=false;$('bodyEnabled').checked=false;settingsChanged();lockResearchControls(true);researchBanner.hidden=false;$('researchStart').disabled=true;$('researchExport').disabled=true;beginResearchBlock();
};
function finishResearch(reason){if(!researchSession)return;if(researchBlock&&!researchBlock.finished){researchBlock.aborted=true;researchBlock.finished=true;}researchSession.active=false;lockResearchControls(false);researchSession.endReason=reason;researchSession.exported=false;researchBanner.hidden=true;$('researchRatings').hidden=true;$('researchExport').disabled=false;$('researchStart').disabled=false;$('bodyEnabled').checked=researchSession.savedBody;settingsChanged();setPhase('look');$('researchStatus').textContent='本轮结束，可导出并自由演奏。认知模型仍未训练；伴奏可手动开启。';}
$('researchCancel').onclick=()=>finishResearch('participant-ended');
$('researchConsent').onchange=()=>{if(!$('researchConsent').checked&&researchRunning())finishResearch('consent-stopped');};
$('researchNext').onclick=()=>{if(!researchRunning()||!researchBlock.finished)return;const attention=$('researchAttention').value,ratings=Object.fromEntries(['confusion','stuck','effort'].map(k=>[k,$('rating-'+k).value]));if(!attention||Object.values(ratings).some(x=>x==='')){toast('请填写各项，允许选择混合／不确定。');return;}researchBlock.report={attention,...ratings,scope:'whole completed block; retrospective'};researchIndex++;if(researchIndex>=researchTasks.length)finishResearch('completed');else beginResearchBlock();};
setInterval(()=>{if(!researchRunning()||!researchBlock||researchBlock.finished)return;if(document.hidden||source!==researchSession.source){finishResearch('interrupted');return;}const elapsed=performance.now()-researchBlock.start,left=Math.max(0,Math.ceil((researchBlock.duration-elapsed)/1000));let cue=researchBlock.kind==='baseline'?'自然观看桌垫，保持照明与位置':researchBlock.kind==='memory'&&elapsed>6000?'按记忆重复旋律；忘记也没关系':researchBlock.notes.map(n=>n+1).join(' → ');const msg=`${researchIndex<0?'参考采集':`跟奏 ${researchIndex+1}/6 · ${researchBlock.kind==='memory'?'记忆':'可见'}旋律`} · ${left} 秒 · ${cue}`;researchBanner.textContent=msg;$('researchStatus').textContent=msg;if(left===0){researchBlock.finished=true;researchBlock.summary={samples:researchBlock.samples.length,validFraction:researchBlock.samples.length?researchBlock.samples.filter(s=>s.worn&&s.surfaceValid).length/researchBlock.samples.length:0};setPhase('prepare');instrument.stop();if(researchIndex<0){const values=researchBlock.samples.map(s=>pupil(s)).filter(v=>v!==null).sort((a,b)=>a-b);if(values.length>=150){baseline=values[Math.floor(values.length/2)];baselineReady=true;smoothed=baseline;researchBlock.pupilReference=baseline;}researchIndex=0;beginResearchBlock();}else{$('researchRatings').hidden=false;researchBanner.textContent='本段结束，请在研究面板标记感受';}}},150);
$('researchExport').onclick=()=>{if(!researchSession||researchRunning())return;const blob=new Blob([JSON.stringify(researchSession)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='donut-midi-research-'+researchSession.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);researchSession.exported=true;};
window.addEventListener('beforeunload',e=>{if(researchSession&&!researchSession.exported){e.preventDefault();e.returnValue='';}});
