'use strict';
const studyPanel=document.createElement('section');studyPanel.className='panel';studyPanel.innerHTML=`<h2>Participant sessions · local database</h2><p>Enter any participant ID. Record game performance and eye measurements, then report your experience. No video or automatic mental-state labels.</p><button id="studyOpen">Start participant test</button><button id="studyEnd" disabled>End test & self-report</button><p id="studyStatus" role="status">Not collecting. Connector 1.3 or later is required, including for mouse tests.</p><button id="studyList">Refresh saved tests</button><button id="studyExportAll">Export all CSVs to this computer</button><button id="studyRetry">Retry save with current pairing</button><p id="studyPath"></p><div id="studyHistory"></div>`;panels.research.prepend(studyPanel);
const studyQuick=document.createElement('button');studyQuick.id='studyQuick';studyQuick.textContent='Participant test';$('gameToggle').after(studyQuick);studyQuick.onclick=()=>studyRecorder?finishStudy('participant_ended'):openStudy();
const studyDialog=document.createElement('dialog');studyDialog.id='studyDialog';studyDialog.innerHTML=`<form method="dialog"><button style="float:right" aria-label="Close participant dialog">×</button></form><div id="studySetup"><h2>Start a participant test</h2><label>Participant ID (not necessarily a name)<input id="studyParticipant" maxlength="128" autocomplete="off" placeholder="e.g. P01 or your own code"></label><p>Eye samples (~10 Hz), game targets, timing and self-reports will be saved to this computer. No videos, no cloud upload. The same ID can have multiple tests.</p><label><input type="checkbox" id="studyConsent">I agree to this local data collection.</label><p id="studyCheck"></p><p>A Signals reference is optional. Without a valid reference we save raw pupil diameter only. Entering Game Mode invalidates a prior reference; pupil changes are not mental-state scores.</p><button id="studyBegin" type="button">Begin test & open game</button></div><div id="studyReport" hidden><h2>How was this test?</h2><p>Describe the whole test, not individual notes. “Unsure” is a valid answer.</p><p id="studyResult"></p><div id="studyRatings"></div><label>Notes (optional)<textarea id="studyNotes" maxlength="1000"></textarea></label><button id="studySave" type="button">Save report & finish</button><p id="studySaveStatus" role="status"></p><button id="studyExportOne" type="button" hidden>Export this test’s CSVs to this computer</button></div>`;document.body.append(studyDialog);
const studyStyle=document.createElement('style');studyStyle.textContent='#studyDialog{width:min(520px,90vw);max-height:85vh;overflow:auto;border:1px solid #d8d0c6;border-radius:18px;padding:24px;color:#342e28;background:#fffcf7}#studyDialog::backdrop{background:#211a1666}#studyDialog label{display:block;margin:10px 0}#studyDialog input:not([type=checkbox]),#studyDialog select,#studyDialog textarea{width:100%;box-sizing:border-box;padding:8px}#studyDialog p{font-size:13px;line-height:1.5}#studyBegin,#studySave{padding:10px 16px;background:#bd3c26;color:white}#studyQuick{width:100%;margin-top:5px;font-size:11px;padding:7px}#studyHistory{font-size:11px;max-height:220px;overflow:auto}#studyPath{font-size:11px;overflow-wrap:anywhere}';document.head.append(studyStyle);
for(const [key,label] of [['attention','Attention to the task'],['effort','Mental effort'],['confusion','Confusion'],['stuck','Feeling stuck'],['relaxation','Relaxation'],['stress','Stress']]){const l=document.createElement('label');l.textContent=label;const select=document.createElement('select');select.id='studyRating-'+key;select.add(new Option('Choose…',''));for(let i=1;i<=5;i++)select.add(new Option(`${i}${i===1?' · very low':i===5?' · very high':''}`,String(i)));select.add(new Option('Unsure / mixed','unsure'));l.append(select);$('studyRatings').append(l);}
let studyRecorder=null,studyCredentials=null,studyPending=null,studySending=false,studyFinal=null,studySavedId=null,studySetupBusy=false,studyStartRequest=null,studyFlushFailures=0,studyResearchSignature='';
function studyStatus(message){$('studyStatus').textContent=message;if(message.startsWith('NOT SAVED')){$('recordBadge').textContent='Study · save pending';$('recordBadge').classList.add('recording');}else if(message.startsWith('Collecting'))$('recordBadge').textContent='● Study collecting';}
function studyAuth(){const token=$('pairCode').value.trim(),port=Number($('pairPort').value);if(!/^[A-Za-z0-9_-]{32,128}$/.test(token)||!Number.isInteger(port)||port<1024||port>65535)throw Error('Open Connector 1.3 and paste its pairing code and port under Connect first.');return {token,port};}
async function studyRequest(path,body,credentials=studyCredentials||studyAuth(),zip=false){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(`http://127.0.0.1:${credentials.port}/study/${path}`,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+credentials.token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,credentials:'omit',cache:'no-store',signal:controller.signal,targetAddressSpace:'loopback'});if(!r.ok){let msg='';try{msg=(await r.json()).error||'';}catch{}throw Error(r.status===404?'Update the Neon connector to version 1.3, then reopen its pairing link.':r.status===401?'Pairing code expired. Reopen the connector link, then retry.':msg||`Local database error (${r.status})`);}return zip?r.blob():r.json();}finally{clearTimeout(timer);}}
let studyDownloadUrl=null;
function studyDownload(blob,name){if(studyDownloadUrl)URL.revokeObjectURL(studyDownloadUrl);studyDownloadUrl=URL.createObjectURL(blob);const container=studyDialog.open?$('studySaveStatus'):$('studyStatus');container.replaceChildren();const a=document.createElement('a');a.href=studyDownloadUrl;a.download=name;a.textContent='CSV package ready — click here to download';a.id='studyDownloadLink';container.append(a);a.click();}

async function openStudy(){if(studyRecorder){studyDialog.showModal();return;}if(gameSession&&!gameSession.done)pauseGame('participant setup');$('studySetup').hidden=false;$('studyReport').hidden=true;$('studyCheck').textContent='Checking local database…';$('studyBegin').disabled=true;studyDialog.showModal();try{const info=await studyRequest('info',null,studyAuth());$('studyPath').textContent=info.database_path;$('studyCheck').textContent=source==='live'?'Neon input selected. You can open the game now; it will wait for valid gaze and the four markers after this dialog closes.':'Mouse simulation selected: stored as synthetic; no real pupil statistics.';$('studyBegin').disabled=false;}catch(e){$('studyCheck').textContent=e.message;}}
$('studyOpen').onclick=openStudy;
$('studyBegin').onclick=async()=>{if(studySetupBusy||studyRecorder)return;const pid=$('studyParticipant').value.trim();if(!pid||!$('studyConsent').checked){$('studyCheck').textContent='Enter an ID and agree to collection first.';return;}if(!['simulate','live'].includes(source)||researchRunning()||recording||calibrating||cognitiveEvidence.capture||studioDemo){$('studyCheck').textContent='Finish other recording, research, calibration or demos first; use live Neon or mouse input.';return;}// Setup can cover the mat markers. Authenticate storage now; gameplay gates on fresh, worn, located gaze after the dialog closes.

 studySetupBusy=true;$('studyBegin').disabled=true;
 try{studyCredentials=studyAuth();const meta=studyStartRequest&&studyStartRequest.participant_id===pid&&studyStartRequest.source===source?studyStartRequest:{id:crypto.randomUUID(),participant_id:pid,source,consent:true,consent_version:'local-study-1',schema:'donut-study/1',app_version:'study-2',baseline_mm:cognitiveEvidence.reference};studyStartRequest=meta;await studyRequest('start',meta);studyStartRequest=null;studyRecorder=new DonutStudy.StudyRecorder(meta,performance.now());$('recordBadge').textContent='● Study collecting';$('recordBadge').classList.add('recording');studyFinal=null;studyPending=null;studySavedId=null;studyFlushFailures=0;studyResearchSignature='';$('studyEnd').disabled=false;$('studyOpen').disabled=true;studyQuick.textContent='● End test & self-report';studyStatus('Collecting locally · '+pid);studyDialog.close();if(!document.body.classList.contains('controller-mode'))await toggleController(true);if(!gameEnabled)enterGame();else stopGameForEdit();toast('Test started. Choose your song and press Start Gaze Play.');}catch(e){$('studyCheck').textContent=e.message;}finally{studySetupBusy=false;$('studyBegin').disabled=false;}
};
function captureStudyEvent(type,payload){if(studyRecorder&&!studyFinal)studyRecorder.event(type,payload,performance.now());}
function finishStudy(reason){if(!studyRecorder||studyFinal)return;studyRecorder.observeGame(gameEnabled?gameSession:null,performance.now(),gameNow());studyFinal={reason,at:performance.now(),report:null};studyRecorder.closed=true;$('recordBadge').textContent='Study · report pending';$('recordBadge').classList.remove('recording');if(gameSession&&!gameSession.done)pauseGame('test ended; complete self-report');if(researchRunning())finishResearch('participant-test-ended');$('studySetup').hidden=true;$('studyReport').hidden=false;$('studySave').disabled=false;$('studyExportOne').hidden=true;$('studySaveStatus').textContent='Collection stopped. Samples are being saved; complete the report to finalize.';for(const el of $('studyRatings').querySelectorAll('select'))el.value='';$('studyNotes').value='';const played=studyRecorder.blocks.filter(b=>!b.automatic_preview),completed=played.filter(b=>b.completed);$('studyResult').textContent=`${completed.length}/${played.length} game blocks completed · ${completed.filter(b=>b.early_ready).length} confirmed early · ${studyRecorder.sampleN} samples. `+(studyRecorder.pupilCount?`Mean pupil: ${(studyRecorder.pupilSum/studyRecorder.pupilCount).toFixed(2)} mm; range: ${studyRecorder.pupilMin.toFixed(2)}–${studyRecorder.pupilMax.toFixed(2)} mm; valid pupils: ${Math.round(studyRecorder.pupilCount/studyRecorder.sampleN*100)}%.`:'No valid real pupil measurements (mouse mode or unavailable data).');if(!studyDialog.open)studyDialog.showModal();studyQuick.textContent='Complete self-report';studyStatus('Collection stopped · awaiting whole-test self-report');flushStudy();}
$('studyEnd').onclick=()=>finishStudy('participant_ended');
studyQuick.onclick=()=>{if(studyFinal){if(!studyDialog.open)studyDialog.showModal();}else if(studyRecorder)finishStudy('participant_ended');else openStudy();};
$('studySave').onclick=async()=>{if(!studyRecorder||!studyFinal)return;const report={};for(const el of $('studyRatings').querySelectorAll('select')){if(!el.value){$('studySaveStatus').textContent='Complete each rating; Unsure / mixed is allowed.';return;}report[el.id.replace('studyRating-','')]=el.value==='unsure'?'unsure':Number(el.value);}report.notes=$('studyNotes').value;studyFinal.report=report;$('studySave').disabled=true;await flushStudy();};
async function flushStudy(){if(!studyRecorder||studySending)return;studySending=true;
 try{do{if(!studyPending){const last=studyRecorder.samples.length<=500&&studyRecorder.events.length<=1000;studyPending={id:studyRecorder.meta.id,batch_id:crypto.randomUUID(),samples:studyRecorder.samples.slice(0,500),events:studyRecorder.events.slice(0,1000),snapshot:studyRecorder.snapshot(studyFinal?.at||performance.now(),studyFinal?.report||null,studyFinal?.reason||null),status:last&&studyFinal?.report?(studyFinal.reason==='completed'?'completed':'ended_early'):'in_progress'};}
   await studyRequest('batch',studyPending);studyRecorder.samples.splice(0,studyPending.samples.length);studyRecorder.events.splice(0,studyPending.events.length);const done=studyPending.status!=='in_progress';studyPending=null;studyFlushFailures=0;
   if(done){studySavedId=studyRecorder.meta.id;studyRecorder=null;studyFinal=null;$('studySaveStatus').textContent='Saved to this computer. You can close this panel or download the CSV package.';$('studyExportOne').hidden=false;$('studyOpen').disabled=false;$('studyEnd').disabled=true;studyQuick.textContent='Participant test';studyStatus('Test and self-report saved to the local database.');$('recordBadge').textContent='Study saved locally';$('studyConsent').checked=false;$('studyParticipant').value='';break;}
   studyStatus(studyFinal?'Samples saved · awaiting self-report':'Collecting · '+studyRecorder.meta.participant_id+' · saved through sample '+(studyRecorder.sampleN-studyRecorder.samples.length));
  }while(studyRecorder&&(studyRecorder.samples.length>0||studyRecorder.events.length>0||studyFinal?.report));
 }catch(e){studyFlushFailures++;studyStatus('NOT SAVED: '+e.message+' Keep this page open; automatic retry every 2 seconds.');$('studySaveStatus').textContent='Save pending: '+e.message;$('studySave').disabled=false;if(studyRecorder.samples.length>=3000&&!studyFinal)finishStudy('storage_unavailable');}
 finally{studySending=false;}}
setInterval(flushStudy,2000);
setInterval(()=>{if(!studyRecorder||studyFinal)return;const now=performance.now();if(source!==studyRecorder.meta.source){finishStudy('input_source_changed');return;}if(document.hidden)return;
 studyRecorder.observeGame(gameEnabled?gameSession:null,now,gameNow());const fresh=!!sample&&now-sampleReceived<500;
 studyRecorder.sample({sample,fresh,source,reference:cognitiveEvidence.reference,zone:fresh&&sample.surfaceValid?zoneAt(sample.x,sample.y):-1,phase:gameEnabled?gameSession?.phase:null},now);
 if(researchRunning()&&researchBlock){const signature=researchSession.id+':'+researchIndex+':'+JSON.stringify(researchBlock.report||null);if(signature!==studyResearchSignature){studyResearchSignature=signature;captureStudyEvent('guided_research',{research_id:researchSession.id,block_index:researchIndex,kind:researchBlock.kind,report:researchBlock.report||null});}}
 if(gameEnabled&&gameSession?.done&&!gameSession.automatic)finishStudy('completed');else if(now-studyRecorder.start>30*60*1000)finishStudy('30_minute_limit');
},100);
$('studyList').onclick=async()=>{try{const info=await studyRequest('info',null,studyAuth());$('studyPath').textContent=info.database_path;const result=await studyRequest('list',null,studyAuth());$('studyHistory').replaceChildren();for(const s of result.sessions){const p=document.createElement('p');p.textContent=`${s.participant_id} · ${s.created_at} · ${s.status==='in_progress'?'unfinished / in progress':s.status}`;const b=document.createElement('button');b.textContent='CSV';b.onclick=()=>exportStudy(s.id);p.append(b);$('studyHistory').append(p);}if(!result.sessions.length)$('studyHistory').textContent='No saved tests yet.';}catch(e){studyStatus(e.message);}};
async function exportStudy(id){try{const result=await studyRequest('export-files',id?{id}:{},studyAuth());const container=studyDialog.open?$('studySaveStatus'):$('studyStatus');container.replaceChildren();const message=document.createElement('p');message.style.overflowWrap='anywhere';message.textContent='CSV files saved to: '+result.directory+' · ZIP: '+result.zip_path;const download=document.createElement('button');download.textContent='Also download ZIP in browser';download.onclick=async()=>{try{const blob=await studyRequest('export'+(id?'?id='+encodeURIComponent(id):''),null,studyAuth(),true);studyDownload(blob,'donut-study-'+(id||'all')+'.zip');}catch(e){studyStatus(e.message);}};container.append(message,download);}catch(e){studyStatus(e.message);if(studyDialog.open)$('studySaveStatus').textContent=e.message;}}
$('studyRetry').onclick=async()=>{try{studyCredentials=studyAuth();await studyRequest('info');await flushStudy();}catch(e){studyStatus(e.message);}};
$('studyExportAll').onclick=()=>exportStudy();$('studyExportOne').onclick=()=>exportStudy(studySavedId);
document.addEventListener('visibilitychange',()=>captureStudyEvent(document.hidden?'visibility_pause':'visibility_resume',{}));
window.addEventListener('beforeunload',e=>{if(studyRecorder){e.preventDefault();e.returnValue='';}});
