const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
// Strict fake AudioScheduledSourceNode catches illegal scheduling before start.
class Param{constructor(){this.value=0;}setValueAtTime(v){this.value=v;}linearRampToValueAtTime(v){this.value=v;}exponentialRampToValueAtTime(v){this.value=v;}setTargetAtTime(v){this.value=v;}cancelScheduledValues(){}}
class Node{constructor(){for(const p of ['gain','frequency','detune','threshold','ratio'])this[p]=new Param();}connect(){}disconnect(){}start(){this.started=true;}stop(){if(!this.started)throw Error('stop before start');}}
class AudioContext{constructor(){this.currentTime=0;this.sampleRate=48000;this.destination=new Node();}createBuffer(channels,length){const data=new Float32Array(length);return {getChannelData:()=>data};}createBufferSource(){return new Node();}async decodeAudioData(data){if(data.fail)throw Error("decode failed");return data;}createGain(){return new Node();}createOscillator(){return new Node();}createBiquadFilter(){return new Node();}createDynamicsCompressor(){return new Node();}async resume(){}}
const source=fs.readFileSync(require.resolve('../app.js'),'utf8');const start=source.indexOf('class Instrument{'),end=source.indexOf('\nconst instrument=',start);
function setup(body=true,mapping='brightness'){const ctx={window:{AudioContext},config:{volume:.35,body,mapping,notes:[60,62,64,65,67,69,71]},audioEnabled:true,clamp:(x,a,b)=>Math.max(a,Math.min(b,x))};vm.createContext(ctx);vm.runInContext(source.slice(start,end)+'\nthis.Instrument=Instrument;',ctx);return ctx;}
test('notes schedule legally, held notes release, neutral modulation has no vibrato',async()=>{const c=setup();const i=new c.Instrument();await i.start();const v=i.voice(60);assert.equal(v.osc.frequency.value,261.6255653005986);i.sustain(64);assert.ok(i.hold.held);i.stop();assert.equal(i.hold,null);c.config.mapping='vibrato';i.update(0);assert.equal(v.depth.gain.value,0);i.update(.5);assert.equal(v.depth.gain.value,15);});

test('uploaded clips retrigger, overlap other zones and stop with the instrument',async()=>{const c=setup(),i=new c.Instrument();await i.start();const clip={duration:2,length:96000,numberOfChannels:1};await i.loadSample(0,{name:'one.wav',size:50,arrayBuffer:async()=>clip});await i.loadSample(1,{name:'two.wav',size:50,arrayBuffer:async()=>clip});const a=i.playZone(0),b=i.playZone(1);assert.equal(a.osc.buffer,clip);i.playZone(0);assert.equal(a.released,true);assert.equal(b.released,undefined);i.update(.1);i.stop();assert.ok(i.voices.every(v=>v.released));i.sustainZone(0);assert.equal(i.hold.osc.loop,true);i.clearSample(0);assert.equal(i.samples.has(0),false);assert.equal(i.playZone(0).sample,undefined);});
test('invalid and oversized clips preserve existing sample; clear cancels pending decode',async()=>{const i=new (setup().Instrument)();await i.start();i.samples.set(0,{name:'kept',buffer:{duration:1,length:48000,numberOfChannels:1}});await assert.rejects(i.loadSample(0,{size:26*1024*1024}),/25 MB/);await assert.rejects(i.loadSample(0,{size:1,arrayBuffer:async()=>({duration:61})}),/60 秒/);await assert.rejects(i.loadSample(0,{size:1,arrayBuffer:async()=>({fail:true})}),/decode failed/);assert.equal(i.samples.get(0).name,'kept');let resolve;const p=i.loadSample(0,{size:1,arrayBuffer:()=>new Promise(r=>resolve=r)});while(!resolve)await Promise.resolve();i.clearSample(0);resolve({duration:1,length:48000,numberOfChannels:1});assert.equal(await p,false);assert.equal(i.samples.has(0),false);});

test('guitar creates a decaying plucked buffer and can be stopped',async()=>{const i=new (setup().Instrument)();await i.start();const v=i.voice(60,false,'guitar');assert.equal(v.tone,'guitar');const data=v.osc.buffer.getChannelData(0);assert.ok(data.some(x=>x!==0));assert.ok([...data].every(Number.isFinite));i.update(0);i.stop();assert.equal(v.released,true);});
