const {test}=require('node:test'),assert=require('node:assert/strict');
const {CognitiveEvidence}=require('../cognitive-evidence.js');
const signal={context:'live',stable:true,paused:false,fresh:true,worn:true,left:4,right:4};
function baseline(e){e.start(0);for(let t=0;t<=30000;t+=250)e.update(t,signal);}
test('reference and subsequent pupil change retain physical meaning without a cognitive label',()=>{const e=new CognitiveEvidence();baseline(e);assert.equal(e.reference,4);let out;for(let t=30250;t<=41000;t+=250)out=e.update(t,{...signal,left:4.4,right:4.4});assert.ok(Math.abs(out.summary-10)<1e-9);assert.equal(out.probability,undefined);assert.equal(out.state,undefined);});
test('unworn, stale, missing and monocular data leave gaps, never relaxation',()=>{const e=new CognitiveEvidence();baseline(e);for(const patch of [{fresh:false},{worn:false},{left:null},{right:NaN}]){const o=e.update(31000,{...signal,...patch});assert.equal(o.delta,null);assert.equal(o.summary,null);assert.equal(o.raw,null);}});
test('reference rejects insufficient coverage and notes during capture',()=>{const e=new CognitiveEvidence();e.start(0);for(let t=0;t<=30000;t+=250)e.update(t,{...signal,fresh:t<10000});assert.equal(e.reference,null);e.start(31000);e.event(32000,'note');assert.equal(e.capture,null);assert.equal(e.reference,null);});
test('context and condition changes invalidate reference and old delta values',()=>{for(const change of [{context:'simulate'},{context:'replay'},{context:'synthetic'},{stable:false},{paused:true}]){const e=new CognitiveEvidence();baseline(e);e.update(31000,signal);e.update(32000,{...signal,...change});assert.equal(e.reference,null);assert.ok(e.rows.every(r=>r.delta===null));if(change.context)assert.equal(e.rows.at(-1).raw,null);}});
test('event and signal history is bounded; note markers do not modify pupil evidence',()=>{const e=new CognitiveEvidence();baseline(e);e.event(31000,'note');let o=e.update(31250,signal);assert.equal(o.notes,1);assert.equal(o.delta,0);o=e.update(62000,signal);assert.equal(o.notes,0);assert.ok(e.rows.every(r=>r.time>=32000));});
